[package]
name = "filpy01"
version = "0.1.0"
authors = ["Mashariq Khan <Mashariq.Khan@eastbay.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
